### ISSUE TITLE
プロジェクトのセットアップ

### ISSUE THREAD

**Issue by yy05853** [yy05853/demo#28]
# 作業ログ

## 結論

セットアップはできたが、フロント側のコマンドを実行するときはターミナルを使うこと。
（VSCodeだとNode.jsが古いのでコマンドを実行できない）

フロントのビルド結果をSpring Bootのstaticディレクトリに出力する方法はこちら
https://zenn.dev/takasqr/scraps/02c8e9e3d9d541

## 古いコマンドで四苦八苦していたログ
https://github.com/yy05853/demo/issues/28#issuecomment-1980710764

**Comment by yy05853** [comment]
# 作業ログ※古いコマンドで四苦八苦していたログ

vue create my-project

```
/home/c05853yy/demo/demo/my-project/babel.config.js
  0:0  error  Parsing error: [BABEL] /home/c05853yy/demo/demo/my-project/babel.config.js: Unexpected token '.' (While processing: "/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-plugin-babel/preset.js")

/home/c05853yy/demo/demo/my-project/src/App.vue
  0:0  error  Parsing error: [BABEL] /home/c05853yy/demo/demo/my-project/src/App.vue: Unexpected token '.' (While processing: "/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-plugin-babel/preset.js")

/home/c05853yy/demo/demo/my-project/src/components/HelloWorld.vue
  0:0  error  Parsing error: [BABEL] /home/c05853yy/demo/demo/my-project/src/components/HelloWorld.vue: Unexpected token '.' (While processing: "/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-plugin-babel/preset.js")

/home/c05853yy/demo/demo/my-project/src/main.js
  0:0  error  Parsing error: [BABEL] /home/c05853yy/demo/demo/my-project/src/main.js: Unexpected token '.' (While processing: "/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-plugin-babel/preset.js")

/home/c05853yy/demo/demo/my-project/vue.config.js
  0:0  error  Parsing error: [BABEL] /home/c05853yy/demo/demo/my-project/vue.config.js: Unexpected token '.' (While processing: "/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-plugin-babel/preset.js")

✖ 5 problems (5 errors, 0 warnings)
```

https://qiita.com/tokuyama-shouta/items/2379a4b6639654b09569

---

```
c05853yy@penguin:~/demo/demo/my-project$ npm run build

> my-project@0.1.0 build /home/c05853yy/demo/demo/my-project
> vue-cli-service build

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


✔  Building for production...
 ERROR  Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/c05853yy/demo/demo/my-project/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/c05853yy/demo/demo/my-project/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/config/base.js:154:16
    at /home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/commands/build/index.js:69:13
    at Service.run (/home/c05853yy/demo/demo/my-project/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/c05853yy/.npm/_logs/2024-02-27T23_49_12_662Z-debug.log
c05853yy@penguin:~/demo/demo/my-project$
```

https://stackoverflow.com/questions/70386501/error-vitejs-plugin-vue-requires-vue-3-2-13-or-vue-compiler-sfc-to-be-pre

```
npm i vue@3.2.26
```

---

vueのバージョンが上がらないので、一旦アンインストールする

```
npm uninstall --global @vue/cli
```

---

再インストール

```
npm install -g @vue/cli
```
